name:                swizzle
version:             0.1.0.1
github:              "YoshikuniJujo/swizzle"
license:             BSD-3-Clause
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "(c) 2025 Yoshikuni Jujo"

extra-source-files: []

extra-doc-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Swizzle functions
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/swizzle#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell < 3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Data.Curry
    - Data.Curry.TH
    - Data.Swizzle
    - Data.Swizzle.TH
    - Data.Swizzle.Class

tests:
  swizzle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - swizzle
